"""
HealthTech Shield Synthetic Patient Cohort v1 (HTS-SYN-001)
30 Synthetic Patient Records for Cybersecurity Research & Baseline Training.

IMPORTANT:
- Synthetic research/demo dataset only.
- No real patient PHI / names / emails / addresses.
- Every record has synthetic = True.
"""

SYNTHETIC_PATIENTS_COHORT_V1 = [
    # LOW EXPOSURE PATIENTS (8 Patients: P001 - P008)
    {
        "patient_id": "P001",
        "synthetic": True,
        "display_name": "Patient Alpha",
        "age": 54,
        "sex": "Male",
        "city": "Mumbai",
        "occupation": "Software Architect",
        "organization": "Apex Innovations",
        "primary_diagnosis": "Type 2 Diabetes",
        "device_count": 2,
        "device_type": "Laptop + Mobile",
        "operating_system": "Windows 11",
        "browser_type": "Chrome 122",
        "network_type": "Home WiFi",
        "account_age_days": 450,
        "mfa_enabled": True,
        "last_login_days_ago": 1,
        "failed_login_attempts": 1,
        "successful_login_attempts": 18,
        "requests_per_minute": 8,
        "session_duration_minutes": 25,
        "records_accessed": 3,
        "unique_records_accessed": 2,
        "unique_endpoints": 3,
        "api_calls": 32,
        "error_rate": 0.01,
        "device_changes": 0,
        "password_reset_count": 0,
        "unusual_access_time": False,
        "endpoint_enumeration": False,
        "privilege_escalation_attempts": 0,
        "data_export_events": 0,
        "suspicious_downloads": 0,
        "geographic_anomaly": False,
        "session_anomaly": False,
        "security_profile": "LOW"
    },
    {
        "patient_id": "P002",
        "synthetic": True,
        "display_name": "Patient Beta",
        "age": 62,
        "sex": "Female",
        "city": "Bengaluru",
        "occupation": "Civil Engineer",
        "organization": "Zenith Labs",
        "primary_diagnosis": "Hypertension",
        "device_count": 1,
        "device_type": "Laptop Only",
        "operating_system": "macOS Sonoma",
        "browser_type": "Safari 17",
        "network_type": "Home WiFi",
        "account_age_days": 620,
        "mfa_enabled": True,
        "last_login_days_ago": 2,
        "failed_login_attempts": 0,
        "successful_login_attempts": 22,
        "requests_per_minute": 10,
        "session_duration_minutes": 30,
        "records_accessed": 4,
        "unique_records_accessed": 3,
        "unique_endpoints": 4,
        "api_calls": 40,
        "error_rate": 0.01,
        "device_changes": 0,
        "password_reset_count": 0,
        "unusual_access_time": False,
        "endpoint_enumeration": False,
        "privilege_escalation_attempts": 0,
        "data_export_events": 0,
        "suspicious_downloads": 0,
        "geographic_anomaly": False,
        "session_anomaly": False,
        "security_profile": "LOW"
    },
    {
        "patient_id": "P003",
        "synthetic": True,
        "display_name": "Patient Gamma",
        "age": 29,
        "sex": "Male",
        "city": "Delhi",
        "occupation": "High School Teacher",
        "organization": "Nexus Logistics",
        "primary_diagnosis": "Asthma",
        "device_count": 2,
        "device_type": "Mobile + Tablet",
        "operating_system": "iOS 17",
        "browser_type": "Safari 17",
        "network_type": "Cellular 5G",
        "account_age_days": 310,
        "mfa_enabled": True,
        "last_login_days_ago": 1,
        "failed_login_attempts": 0,
        "successful_login_attempts": 14,
        "requests_per_minute": 6,
        "session_duration_minutes": 18,
        "records_accessed": 2,
        "unique_records_accessed": 2,
        "unique_endpoints": 2,
        "api_calls": 24,
        "error_rate": 0.00,
        "device_changes": 0,
        "password_reset_count": 0,
        "unusual_access_time": False,
        "endpoint_enumeration": False,
        "privilege_escalation_attempts": 0,
        "data_export_events": 0,
        "suspicious_downloads": 0,
        "geographic_anomaly": False,
        "session_anomaly": False,
        "security_profile": "LOW"
    },
    {
        "patient_id": "P004",
        "synthetic": True,
        "display_name": "Patient Delta",
        "age": 35,
        "sex": "Female",
        "city": "Pune",
        "occupation": "Financial Analyst",
        "organization": "Meridian Global",
        "primary_diagnosis": "Migraine",
        "device_count": 2,
        "device_type": "Workstation + Mobile",
        "operating_system": "Windows 11",
        "browser_type": "Chrome 122",
        "network_type": "Home WiFi",
        "account_age_days": 540,
        "mfa_enabled": True,
        "last_login_days_ago": 3,
        "failed_login_attempts": 1,
        "successful_login_attempts": 16,
        "requests_per_minute": 12,
        "session_duration_minutes": 28,
        "records_accessed": 5,
        "unique_records_accessed": 4,
        "unique_endpoints": 3,
        "api_calls": 48,
        "error_rate": 0.02,
        "device_changes": 0,
        "password_reset_count": 0,
        "unusual_access_time": False,
        "endpoint_enumeration": False,
        "privilege_escalation_attempts": 0,
        "data_export_events": 0,
        "suspicious_downloads": 0,
        "geographic_anomaly": False,
        "session_anomaly": False,
        "security_profile": "LOW"
    },
    {
        "patient_id": "P005",
        "synthetic": True,
        "display_name": "Patient Epsilon",
        "age": 48,
        "sex": "Male",
        "city": "Hyderabad",
        "occupation": "Graphic Designer",
        "organization": "Horizon Tech",
        "primary_diagnosis": "Iron Deficiency Anemia",
        "device_count": 1,
        "device_type": "Laptop Only",
        "operating_system": "macOS Sonoma",
        "browser_type": "Firefox 123",
        "network_type": "Home WiFi",
        "account_age_days": 280,
        "mfa_enabled": True,
        "last_login_days_ago": 1,
        "failed_login_attempts": 0,
        "successful_login_attempts": 12,
        "requests_per_minute": 7,
        "session_duration_minutes": 22,
        "records_accessed": 3,
        "unique_records_accessed": 3,
        "unique_endpoints": 2,
        "api_calls": 30,
        "error_rate": 0.01,
        "device_changes": 0,
        "password_reset_count": 0,
        "unusual_access_time": False,
        "endpoint_enumeration": False,
        "privilege_escalation_attempts": 0,
        "data_export_events": 0,
        "suspicious_downloads": 0,
        "geographic_anomaly": False,
        "session_anomaly": False,
        "security_profile": "LOW"
    },
    {
        "patient_id": "P006",
        "synthetic": True,
        "display_name": "Patient Zeta",
        "age": 41,
        "sex": "Female",
        "city": "Chennai",
        "occupation": "Research Scientist",
        "organization": "Veritas Health",
        "primary_diagnosis": "Hypothyroidism",
        "device_count": 2,
        "device_type": "Laptop + Mobile",
        "operating_system": "Linux Ubuntu",
        "browser_type": "Chrome 122",
        "network_type": "Hospital WiFi",
        "account_age_days": 720,
        "mfa_enabled": True,
        "last_login_days_ago": 2,
        "failed_login_attempts": 1,
        "successful_login_attempts": 25,
        "requests_per_minute": 11,
        "session_duration_minutes": 35,
        "records_accessed": 4,
        "unique_records_accessed": 3,
        "unique_endpoints": 4,
        "api_calls": 52,
        "error_rate": 0.01,
        "device_changes": 0,
        "password_reset_count": 0,
        "unusual_access_time": False,
        "endpoint_enumeration": False,
        "privilege_escalation_attempts": 0,
        "data_export_events": 0,
        "suspicious_downloads": 0,
        "geographic_anomaly": False,
        "session_anomaly": False,
        "security_profile": "LOW"
    },
    {
        "patient_id": "P007",
        "synthetic": True,
        "display_name": "Patient Eta",
        "age": 58,
        "sex": "Male",
        "city": "Kolkata",
        "occupation": "Pharmacist",
        "organization": "Starlight Systems",
        "primary_diagnosis": "Osteoarthritis",
        "device_count": 1,
        "device_type": "Desktop PC",
        "operating_system": "Windows 11",
        "browser_type": "Edge 122",
        "network_type": "Home WiFi",
        "account_age_days": 890,
        "mfa_enabled": True,
        "last_login_days_ago": 4,
        "failed_login_attempts": 0,
        "successful_login_attempts": 15,
        "requests_per_minute": 9,
        "session_duration_minutes": 24,
        "records_accessed": 2,
        "unique_records_accessed": 2,
        "unique_endpoints": 3,
        "api_calls": 36,
        "error_rate": 0.02,
        "device_changes": 0,
        "password_reset_count": 0,
        "unusual_access_time": False,
        "endpoint_enumeration": False,
        "privilege_escalation_attempts": 0,
        "data_export_events": 0,
        "suspicious_downloads": 0,
        "geographic_anomaly": False,
        "session_anomaly": False,
        "security_profile": "LOW"
    },
    {
        "patient_id": "P008",
        "synthetic": True,
        "display_name": "Patient Theta",
        "age": 67,
        "sex": "Female",
        "city": "Ahmedabad",
        "occupation": "Accountant",
        "organization": "Aura Therapeutics",
        "primary_diagnosis": "Chronic Kidney Disease",
        "device_count": 2,
        "device_type": "Tablet + Mobile",
        "operating_system": "iOS 17",
        "browser_type": "Safari 17",
        "network_type": "Home WiFi",
        "account_age_days": 410,
        "mfa_enabled": True,
        "last_login_days_ago": 1,
        "failed_login_attempts": 1,
        "successful_login_attempts": 19,
        "requests_per_minute": 13,
        "session_duration_minutes": 32,
        "records_accessed": 6,
        "unique_records_accessed": 4,
        "unique_endpoints": 4,
        "api_calls": 44,
        "error_rate": 0.01,
        "device_changes": 0,
        "password_reset_count": 0,
        "unusual_access_time": False,
        "endpoint_enumeration": False,
        "privilege_escalation_attempts": 0,
        "data_export_events": 0,
        "suspicious_downloads": 0,
        "geographic_anomaly": False,
        "session_anomaly": False,
        "security_profile": "LOW"
    },

    # MODERATE EXPOSURE PATIENTS (8 Patients: P009 - P016)
    {
        "patient_id": "P009",
        "synthetic": True,
        "display_name": "Patient Iota",
        "age": 51,
        "sex": "Male",
        "city": "Jaipur",
        "occupation": "Architect",
        "organization": "Vanguard Digital",
        "primary_diagnosis": "Coronary Artery Disease",
        "device_count": 2,
        "device_type": "Laptop + Mobile",
        "operating_system": "Windows 11",
        "browser_type": "Chrome 122",
        "network_type": "Corporate VPN",
        "account_age_days": 340,
        "mfa_enabled": True,
        "last_login_days_ago": 1,
        "failed_login_attempts": 3,
        "successful_login_attempts": 28,
        "requests_per_minute": 22,
        "session_duration_minutes": 45,
        "records_accessed": 9,
        "unique_records_accessed": 7,
        "unique_endpoints": 6,
        "api_calls": 95,
        "error_rate": 0.04,
        "device_changes": 1,
        "password_reset_count": 1,
        "unusual_access_time": False,
        "endpoint_enumeration": False,
        "privilege_escalation_attempts": 0,
        "data_export_events": 0,
        "suspicious_downloads": 0,
        "geographic_anomaly": False,
        "session_anomaly": False,
        "security_profile": "MODERATE"
    },
    {
        "patient_id": "P010",
        "synthetic": True,
        "display_name": "Patient Kappa",
        "age": 42,
        "sex": "Male",
        "city": "Kochi",
        "occupation": "Data Analyst",
        "organization": "Prism Solutions",
        "primary_diagnosis": "GERD",
        "device_count": 3,
        "device_type": "Workstation + Laptop + Mobile",
        "operating_system": "Linux Ubuntu",
        "browser_type": "Firefox 123",
        "network_type": "Corporate VPN",
        "account_age_days": 510,
        "mfa_enabled": True,
        "last_login_days_ago": 2,
        "failed_login_attempts": 2,
        "successful_login_attempts": 34,
        "requests_per_minute": 26,
        "session_duration_minutes": 50,
        "records_accessed": 12,
        "unique_records_accessed": 9,
        "unique_endpoints": 7,
        "api_calls": 110,
        "error_rate": 0.03,
        "device_changes": 1,
        "password_reset_count": 0,
        "unusual_access_time": True,
        "endpoint_enumeration": False,
        "privilege_escalation_attempts": 0,
        "data_export_events": 0,
        "suspicious_downloads": 0,
        "geographic_anomaly": False,
        "session_anomaly": False,
        "security_profile": "MODERATE"
    },
    {
        "patient_id": "P011",
        "synthetic": True,
        "display_name": "Patient Lambda",
        "age": 31,
        "sex": "Female",
        "city": "Chandigarh",
        "occupation": "Operations Manager",
        "organization": "Beacon Networks",
        "primary_diagnosis": "Epilepsy",
        "device_count": 2,
        "device_type": "Laptop + Mobile",
        "operating_system": "macOS Sonoma",
        "browser_type": "Chrome 122",
        "network_type": "Home WiFi",
        "account_age_days": 190,
        "mfa_enabled": False,
        "last_login_days_ago": 1,
        "failed_login_attempts": 4,
        "successful_login_attempts": 25,
        "requests_per_minute": 24,
        "session_duration_minutes": 42,
        "records_accessed": 8,
        "unique_records_accessed": 6,
        "unique_endpoints": 6,
        "api_calls": 88,
        "error_rate": 0.05,
        "device_changes": 1,
        "password_reset_count": 1,
        "unusual_access_time": False,
        "endpoint_enumeration": False,
        "privilege_escalation_attempts": 0,
        "data_export_events": 0,
        "suspicious_downloads": 0,
        "geographic_anomaly": False,
        "session_anomaly": False,
        "security_profile": "MODERATE"
    },
    {
        "patient_id": "P012",
        "synthetic": True,
        "display_name": "Patient Mu",
        "age": 44,
        "sex": "Male",
        "city": "Lucknow",
        "occupation": "Biomedical Engineer",
        "organization": "Cascade Systems",
        "primary_diagnosis": "Psoriasis",
        "device_count": 2,
        "device_type": "Laptop + Tablet",
        "operating_system": "Windows 11",
        "browser_type": "Edge 122",
        "network_type": "Hospital WiFi",
        "account_age_days": 680,
        "mfa_enabled": True,
        "last_login_days_ago": 3,
        "failed_login_attempts": 3,
        "successful_login_attempts": 31,
        "requests_per_minute": 28,
        "session_duration_minutes": 48,
        "records_accessed": 10,
        "unique_records_accessed": 8,
        "unique_endpoints": 7,
        "api_calls": 125,
        "error_rate": 0.04,
        "device_changes": 0,
        "password_reset_count": 0,
        "unusual_access_time": True,
        "endpoint_enumeration": False,
        "privilege_escalation_attempts": 0,
        "data_export_events": 0,
        "suspicious_downloads": 0,
        "geographic_anomaly": False,
        "session_anomaly": False,
        "security_profile": "MODERATE"
    },
    {
        "patient_id": "P013",
        "synthetic": True,
        "display_name": "Patient Nu",
        "age": 60,
        "sex": "Female",
        "city": "Indore",
        "occupation": "Systems Administrator",
        "organization": "Genesis Health",
        "primary_diagnosis": "Rheumatoid Arthritis",
        "device_count": 2,
        "device_type": "Desktop PC + Mobile",
        "operating_system": "Windows 11",
        "browser_type": "Chrome 122",
        "network_type": "Home WiFi",
        "account_age_days": 810,
        "mfa_enabled": True,
        "last_login_days_ago": 1,
        "failed_login_attempts": 2,
        "successful_login_attempts": 29,
        "requests_per_minute": 20,
        "session_duration_minutes": 40,
        "records_accessed": 7,
        "unique_records_accessed": 5,
        "unique_endpoints": 5,
        "api_calls": 82,
        "error_rate": 0.03,
        "device_changes": 1,
        "password_reset_count": 0,
        "unusual_access_time": False,
        "endpoint_enumeration": False,
        "privilege_escalation_attempts": 0,
        "data_export_events": 0,
        "suspicious_downloads": 0,
        "geographic_anomaly": False,
        "session_anomaly": False,
        "security_profile": "MODERATE"
    },
    {
        "patient_id": "P014",
        "synthetic": True,
        "display_name": "Patient Xi",
        "age": 73,
        "sex": "Male",
        "city": "Nagpur",
        "occupation": "Clinical Coordinator",
        "organization": "Titan Dynamics",
        "primary_diagnosis": "COPD",
        "device_count": 1,
        "device_type": "Tablet Only",
        "operating_system": "Android 14",
        "browser_type": "Chrome 122",
        "network_type": "Cellular 5G",
        "account_age_days": 430,
        "mfa_enabled": True,
        "last_login_days_ago": 2,
        "failed_login_attempts": 4,
        "successful_login_attempts": 20,
        "requests_per_minute": 18,
        "session_duration_minutes": 38,
        "records_accessed": 6,
        "unique_records_accessed": 5,
        "unique_endpoints": 4,
        "api_calls": 75,
        "error_rate": 0.05,
        "device_changes": 0,
        "password_reset_count": 1,
        "unusual_access_time": False,
        "endpoint_enumeration": False,
        "privilege_escalation_attempts": 0,
        "data_export_events": 0,
        "suspicious_downloads": 0,
        "geographic_anomaly": False,
        "session_anomaly": False,
        "security_profile": "MODERATE"
    },
    {
        "patient_id": "P015",
        "synthetic": True,
        "display_name": "Patient Omicron",
        "age": 39,
        "sex": "Female",
        "city": "Coimbatore",
        "occupation": "Electrical Engineer",
        "organization": "Orion Cloud",
        "primary_diagnosis": "Fatty Liver Disease",
        "device_count": 2,
        "device_type": "Laptop + Mobile",
        "operating_system": "macOS Sonoma",
        "browser_type": "Safari 17",
        "network_type": "Corporate VPN",
        "account_age_days": 260,
        "mfa_enabled": True,
        "last_login_days_ago": 1,
        "failed_login_attempts": 2,
        "successful_login_attempts": 36,
        "requests_per_minute": 25,
        "session_duration_minutes": 46,
        "records_accessed": 11,
        "unique_records_accessed": 8,
        "unique_endpoints": 6,
        "api_calls": 105,
        "error_rate": 0.03,
        "device_changes": 1,
        "password_reset_count": 0,
        "unusual_access_time": True,
        "endpoint_enumeration": False,
        "privilege_escalation_attempts": 0,
        "data_export_events": 0,
        "suspicious_downloads": 0,
        "geographic_anomaly": False,
        "session_anomaly": False,
        "security_profile": "MODERATE"
    },
    {
        "patient_id": "P016",
        "synthetic": True,
        "display_name": "Patient Pi",
        "age": 52,
        "sex": "Male",
        "city": "Bhopal",
        "occupation": "Urban Planner",
        "organization": "Solstice Media",
        "primary_diagnosis": "Vitamin D Deficiency",
        "device_count": 2,
        "device_type": "Laptop + Mobile",
        "operating_system": "Windows 11",
        "browser_type": "Firefox 123",
        "network_type": "Home WiFi",
        "account_age_days": 390,
        "mfa_enabled": True,
        "last_login_days_ago": 1,
        "failed_login_attempts": 3,
        "successful_login_attempts": 27,
        "requests_per_minute": 21,
        "session_duration_minutes": 44,
        "records_accessed": 8,
        "unique_records_accessed": 6,
        "unique_endpoints": 5,
        "api_calls": 90,
        "error_rate": 0.04,
        "device_changes": 0,
        "password_reset_count": 1,
        "unusual_access_time": False,
        "endpoint_enumeration": False,
        "privilege_escalation_attempts": 0,
        "data_export_events": 0,
        "suspicious_downloads": 0,
        "geographic_anomaly": False,
        "session_anomaly": False,
        "security_profile": "MODERATE"
    },

    # HIGH EXPOSURE PATIENTS (8 Patients: P017 - P024)
    {
        "patient_id": "P017",
        "synthetic": True,
        "display_name": "Patient Rho",
        "age": 61,
        "sex": "Female",
        "city": "Patna",
        "occupation": "Marketing Specialist",
        "organization": "Elysium Tech",
        "primary_diagnosis": "Hyperlipidemia",
        "device_count": 3,
        "device_type": "Laptop + Mobile + Tablet",
        "operating_system": "Windows 11",
        "browser_type": "Chrome 122",
        "network_type": "Hospital WiFi",
        "account_age_days": 150,
        "mfa_enabled": False,
        "last_login_days_ago": 1,
        "failed_login_attempts": 8,
        "successful_login_attempts": 42,
        "requests_per_minute": 65,
        "session_duration_minutes": 60,
        "records_accessed": 24,
        "unique_records_accessed": 18,
        "unique_endpoints": 12,
        "api_calls": 240,
        "error_rate": 0.12,
        "device_changes": 2,
        "password_reset_count": 2,
        "unusual_access_time": True,
        "endpoint_enumeration": True,
        "privilege_escalation_attempts": 0,
        "data_export_events": 1,
        "suspicious_downloads": 1,
        "geographic_anomaly": False,
        "session_anomaly": False,
        "security_profile": "HIGH"
    },
    {
        "patient_id": "P018",
        "synthetic": True,
        "display_name": "Patient Sigma",
        "age": 45,
        "sex": "Male",
        "city": "Vadodara",
        "occupation": "Journalist",
        "organization": "Velox Labs",
        "primary_diagnosis": "Irritable Bowel Syndrome",
        "device_count": 2,
        "device_type": "Workstation + Mobile",
        "operating_system": "Linux Ubuntu",
        "browser_type": "Firefox 123",
        "network_type": "Public WiFi",
        "account_age_days": 210,
        "mfa_enabled": False,
        "last_login_days_ago": 1,
        "failed_login_attempts": 10,
        "successful_login_attempts": 38,
        "requests_per_minute": 72,
        "session_duration_minutes": 55,
        "records_accessed": 28,
        "unique_records_accessed": 21,
        "unique_endpoints": 14,
        "api_calls": 280,
        "error_rate": 0.15,
        "device_changes": 2,
        "password_reset_count": 3,
        "unusual_access_time": True,
        "endpoint_enumeration": True,
        "privilege_escalation_attempts": 0,
        "data_export_events": 0,
        "suspicious_downloads": 2,
        "geographic_anomaly": True,
        "session_anomaly": False,
        "security_profile": "HIGH"
    },
    {
        "patient_id": "P019",
        "synthetic": True,
        "display_name": "Patient Tau",
        "age": 65,
        "sex": "Female",
        "city": "Visakhapatnam",
        "occupation": "Legal Advisor",
        "organization": "Astral Networks",
        "primary_diagnosis": "Osteoporosis",
        "device_count": 2,
        "device_type": "Laptop + Mobile",
        "operating_system": "macOS Sonoma",
        "browser_type": "Safari 17",
        "network_type": "Home WiFi",
        "account_age_days": 490,
        "mfa_enabled": True,
        "last_login_days_ago": 2,
        "failed_login_attempts": 7,
        "successful_login_attempts": 35,
        "requests_per_minute": 58,
        "session_duration_minutes": 52,
        "records_accessed": 22,
        "unique_records_accessed": 16,
        "unique_endpoints": 11,
        "api_calls": 210,
        "error_rate": 0.10,
        "device_changes": 1,
        "password_reset_count": 1,
        "unusual_access_time": False,
        "endpoint_enumeration": True,
        "privilege_escalation_attempts": 0,
        "data_export_events": 1,
        "suspicious_downloads": 1,
        "geographic_anomaly": False,
        "session_anomaly": False,
        "security_profile": "HIGH"
    },
    {
        "patient_id": "P020",
        "synthetic": True,
        "display_name": "Patient Upsilon",
        "age": 56,
        "sex": "Male",
        "city": "Surat",
        "occupation": "Logistics Analyst",
        "organization": "Krypton Health",
        "primary_diagnosis": "Sleep Apnea",
        "device_count": 3,
        "device_type": "Laptop + Tablet + Mobile",
        "operating_system": "Windows 11",
        "browser_type": "Chrome 122",
        "network_type": "Corporate VPN",
        "account_age_days": 370,
        "mfa_enabled": False,
        "last_login_days_ago": 1,
        "failed_login_attempts": 9,
        "successful_login_attempts": 40,
        "requests_per_minute": 68,
        "session_duration_minutes": 58,
        "records_accessed": 26,
        "unique_records_accessed": 19,
        "unique_endpoints": 13,
        "api_calls": 260,
        "error_rate": 0.14,
        "device_changes": 2,
        "password_reset_count": 2,
        "unusual_access_time": True,
        "endpoint_enumeration": True,
        "privilege_escalation_attempts": 0,
        "data_export_events": 1,
        "suspicious_downloads": 2,
        "geographic_anomaly": False,
        "session_anomaly": True,
        "security_profile": "HIGH"
    },
    {
        "patient_id": "P021",
        "synthetic": True,
        "display_name": "Patient Phi",
        "age": 33,
        "sex": "Female",
        "city": "Thiruvananthapuram",
        "occupation": "Quality Lead",
        "organization": "Pinnacle Systems",
        "primary_diagnosis": "Allergic Rhinitis",
        "device_count": 2,
        "device_type": "Laptop + Mobile",
        "operating_system": "Windows 11",
        "browser_type": "Edge 122",
        "network_type": "Hospital WiFi",
        "account_age_days": 180,
        "mfa_enabled": True,
        "last_login_days_ago": 1,
        "failed_login_attempts": 6,
        "successful_login_attempts": 32,
        "requests_per_minute": 54,
        "session_duration_minutes": 48,
        "records_accessed": 19,
        "unique_records_accessed": 15,
        "unique_endpoints": 10,
        "api_calls": 195,
        "error_rate": 0.09,
        "device_changes": 1,
        "password_reset_count": 1,
        "unusual_access_time": True,
        "endpoint_enumeration": True,
        "privilege_escalation_attempts": 0,
        "data_export_events": 0,
        "suspicious_downloads": 1,
        "geographic_anomaly": False,
        "session_anomaly": False,
        "security_profile": "HIGH"
    },
    {
        "patient_id": "P022",
        "synthetic": True,
        "display_name": "Patient Chi",
        "age": 27,
        "sex": "Male",
        "city": "Guwahati",
        "occupation": "HR Specialist",
        "organization": "Nova Digital",
        "primary_diagnosis": "Eczema",
        "device_count": 2,
        "device_type": "Mobile + Tablet",
        "operating_system": "Android 14",
        "browser_type": "Chrome 122",
        "network_type": "Public WiFi",
        "account_age_days": 130,
        "mfa_enabled": False,
        "last_login_days_ago": 2,
        "failed_login_attempts": 11,
        "successful_login_attempts": 30,
        "requests_per_minute": 75,
        "session_duration_minutes": 50,
        "records_accessed": 30,
        "unique_records_accessed": 22,
        "unique_endpoints": 15,
        "api_calls": 290,
        "error_rate": 0.16,
        "device_changes": 2,
        "password_reset_count": 3,
        "unusual_access_time": True,
        "endpoint_enumeration": True,
        "privilege_escalation_attempts": 0,
        "data_export_events": 1,
        "suspicious_downloads": 2,
        "geographic_anomaly": True,
        "session_anomaly": False,
        "security_profile": "HIGH"
    },
    {
        "patient_id": "P023",
        "synthetic": True,
        "display_name": "Patient Psi",
        "age": 23,
        "sex": "Female",
        "city": "Mysuru",
        "occupation": "Mechanical Engineer",
        "organization": "CyberPulse",
        "primary_diagnosis": "PCOS",
        "device_count": 2,
        "device_type": "Laptop + Mobile",
        "operating_system": "Windows 11",
        "browser_type": "Chrome 122",
        "network_type": "Home WiFi",
        "account_age_days": 220,
        "mfa_enabled": True,
        "last_login_days_ago": 1,
        "failed_login_attempts": 8,
        "successful_login_attempts": 34,
        "requests_per_minute": 60,
        "session_duration_minutes": 54,
        "records_accessed": 21,
        "unique_records_accessed": 16,
        "unique_endpoints": 11,
        "api_calls": 215,
        "error_rate": 0.11,
        "device_changes": 1,
        "password_reset_count": 1,
        "unusual_access_time": False,
        "endpoint_enumeration": True,
        "privilege_escalation_attempts": 0,
        "data_export_events": 0,
        "suspicious_downloads": 1,
        "geographic_anomaly": False,
        "session_anomaly": False,
        "security_profile": "HIGH"
    },
    {
        "patient_id": "P024",
        "synthetic": True,
        "display_name": "Patient Omega",
        "age": 49,
        "sex": "Male",
        "city": "Ranchi",
        "occupation": "Environmental Consultant",
        "organization": "Synapse Tech",
        "primary_diagnosis": "Chronic Sinusitis",
        "device_count": 3,
        "device_type": "Workstation + Laptop + Mobile",
        "operating_system": "macOS Sonoma",
        "browser_type": "Safari 17",
        "network_type": "Corporate VPN",
        "account_age_days": 410,
        "mfa_enabled": True,
        "last_login_days_ago": 1,
        "failed_login_attempts": 10,
        "successful_login_attempts": 36,
        "requests_per_minute": 64,
        "session_duration_minutes": 56,
        "records_accessed": 25,
        "unique_records_accessed": 18,
        "unique_endpoints": 13,
        "api_calls": 250,
        "error_rate": 0.13,
        "device_changes": 2,
        "password_reset_count": 2,
        "unusual_access_time": True,
        "endpoint_enumeration": True,
        "privilege_escalation_attempts": 0,
        "data_export_events": 1,
        "suspicious_downloads": 2,
        "geographic_anomaly": False,
        "session_anomaly": True,
        "security_profile": "HIGH"
    },

    # CRITICAL EXPOSURE PATIENTS (6 Patients: P025 - P030)
    {
        "patient_id": "P025",
        "synthetic": True,
        "display_name": "Patient Alpha-2",
        "age": 37,
        "sex": "Female",
        "city": "Dehradun",
        "occupation": "Product Manager",
        "organization": "Frontier Global",
        "primary_diagnosis": "Anemia",
        "device_count": 3,
        "device_type": "Laptop + Mobile + Tablet",
        "operating_system": "Windows 11",
        "browser_type": "Chrome 122",
        "network_type": "Tor/Proxy",
        "account_age_days": 45,
        "mfa_enabled": False,
        "last_login_days_ago": 0,
        "failed_login_attempts": 22,
        "successful_login_attempts": 12,
        "requests_per_minute": 180,
        "session_duration_minutes": 90,
        "records_accessed": 85,
        "unique_records_accessed": 64,
        "unique_endpoints": 28,
        "api_calls": 720,
        "error_rate": 0.32,
        "device_changes": 3,
        "password_reset_count": 4,
        "unusual_access_time": True,
        "endpoint_enumeration": True,
        "privilege_escalation_attempts": 2,
        "data_export_events": 3,
        "suspicious_downloads": 5,
        "geographic_anomaly": True,
        "session_anomaly": True,
        "security_profile": "CRITICAL"
    },
    {
        "patient_id": "P026",
        "synthetic": True,
        "display_name": "Patient Beta-2",
        "age": 47,
        "sex": "Male",
        "city": "Jodhpur",
        "occupation": "Event Planner",
        "organization": "Summit Analytics",
        "primary_diagnosis": "Obesity",
        "device_count": 4,
        "device_type": "Workstation + 2 Laptops + Mobile",
        "operating_system": "Linux Kali",
        "browser_type": "Firefox 123",
        "network_type": "Public WiFi",
        "account_age_days": 30,
        "mfa_enabled": False,
        "last_login_days_ago": 0,
        "failed_login_attempts": 35,
        "successful_login_attempts": 8,
        "requests_per_minute": 240,
        "session_duration_minutes": 110,
        "records_accessed": 120,
        "unique_records_accessed": 92,
        "unique_endpoints": 36,
        "api_calls": 980,
        "error_rate": 0.45,
        "device_changes": 4,
        "password_reset_count": 5,
        "unusual_access_time": True,
        "endpoint_enumeration": True,
        "privilege_escalation_attempts": 3,
        "data_export_events": 5,
        "suspicious_downloads": 8,
        "geographic_anomaly": True,
        "session_anomaly": True,
        "security_profile": "CRITICAL"
    },
    {
        "patient_id": "P027",
        "synthetic": True,
        "display_name": "Patient Gamma-2",
        "age": 23,
        "sex": "Female",
        "city": "Shimla",
        "occupation": "Supply Chain Lead",
        "organization": "Spectra Health",
        "primary_diagnosis": "Chronic Back Pain",
        "device_count": 3,
        "device_type": "Laptop + 2 Mobiles",
        "operating_system": "Android 14",
        "browser_type": "Chrome 122",
        "network_type": "Unencrypted Public Net",
        "account_age_days": 60,
        "mfa_enabled": False,
        "last_login_days_ago": 0,
        "failed_login_attempts": 18,
        "successful_login_attempts": 15,
        "requests_per_minute": 150,
        "session_duration_minutes": 85,
        "records_accessed": 68,
        "unique_records_accessed": 51,
        "unique_endpoints": 24,
        "api_calls": 610,
        "error_rate": 0.28,
        "device_changes": 3,
        "password_reset_count": 3,
        "unusual_access_time": True,
        "endpoint_enumeration": True,
        "privilege_escalation_attempts": 1,
        "data_export_events": 2,
        "suspicious_downloads": 4,
        "geographic_anomaly": True,
        "session_anomaly": True,
        "security_profile": "CRITICAL"
    },
    {
        "patient_id": "P028",
        "synthetic": True,
        "display_name": "Patient Delta-2",
        "age": 68,
        "sex": "Male",
        "city": "Varanasi",
        "occupation": "Database Admin",
        "organization": "Quantum Dynamics",
        "primary_diagnosis": "Glaucoma",
        "device_count": 3,
        "device_type": "Desktop PC + Laptop + Tablet",
        "operating_system": "Windows 11",
        "browser_type": "Edge 122",
        "network_type": "Unknown Anonymized IP",
        "account_age_days": 90,
        "mfa_enabled": False,
        "last_login_days_ago": 0,
        "failed_login_attempts": 28,
        "successful_login_attempts": 10,
        "requests_per_minute": 210,
        "session_duration_minutes": 105,
        "records_accessed": 105,
        "unique_records_accessed": 80,
        "unique_endpoints": 32,
        "api_calls": 860,
        "error_rate": 0.38,
        "device_changes": 3,
        "password_reset_count": 4,
        "unusual_access_time": True,
        "endpoint_enumeration": True,
        "privilege_escalation_attempts": 2,
        "data_export_events": 4,
        "suspicious_downloads": 6,
        "geographic_anomaly": True,
        "session_anomaly": True,
        "security_profile": "CRITICAL"
    },
    {
        "patient_id": "P029",
        "synthetic": True,
        "display_name": "Patient Epsilon-2",
        "age": 36,
        "sex": "Female",
        "city": "Mangaluru",
        "occupation": "Financial Advisor",
        "organization": "InfiniTech Labs",
        "primary_diagnosis": "Fibromyalgia",
        "device_count": 3,
        "device_type": "Laptop + Mobile + Tablet",
        "operating_system": "macOS Sonoma",
        "browser_type": "Safari 17",
        "network_type": "Untrusted Cellular Roaming",
        "account_age_days": 75,
        "mfa_enabled": False,
        "last_login_days_ago": 0,
        "failed_login_attempts": 25,
        "successful_login_attempts": 14,
        "requests_per_minute": 195,
        "session_duration_minutes": 95,
        "records_accessed": 92,
        "unique_records_accessed": 71,
        "unique_endpoints": 30,
        "api_calls": 790,
        "error_rate": 0.34,
        "device_changes": 3,
        "password_reset_count": 3,
        "unusual_access_time": True,
        "endpoint_enumeration": True,
        "privilege_escalation_attempts": 2,
        "data_export_events": 3,
        "suspicious_downloads": 5,
        "geographic_anomaly": True,
        "session_anomaly": True,
        "security_profile": "CRITICAL"
    },
    {
        "patient_id": "P030",
        "synthetic": True,
        "display_name": "Patient Zeta-2",
        "age": 68,
        "sex": "Male",
        "city": "Agra",
        "occupation": "Safety Officer",
        "organization": "Zenith Systems",
        "primary_diagnosis": "Parkinsonian Syndrome",
        "device_count": 4,
        "device_type": "Workstation + 2 Laptops + Mobile",
        "operating_system": "Windows 11",
        "browser_type": "Chrome 122",
        "network_type": "Anonymized Proxy",
        "account_age_days": 20,
        "mfa_enabled": False,
        "last_login_days_ago": 0,
        "failed_login_attempts": 42,
        "successful_login_attempts": 6,
        "requests_per_minute": 290,
        "session_duration_minutes": 120,
        "records_accessed": 140,
        "unique_records_accessed": 105,
        "unique_endpoints": 40,
        "api_calls": 1150,
        "error_rate": 0.52,
        "device_changes": 4,
        "password_reset_count": 6,
        "unusual_access_time": True,
        "endpoint_enumeration": True,
        "privilege_escalation_attempts": 4,
        "data_export_events": 6,
        "suspicious_downloads": 9,
        "geographic_anomaly": True,
        "session_anomaly": True,
        "security_profile": "CRITICAL"
    }
]
